### ISSUE TITLE
passing className from UltimatePagination to WrapperComponent is not implemented

### ISSUE THREAD

**Issue by TrejGun** [ultimate-pagination/react-ultimate-pagination#12]
can you add support of this property?

**Comment by dmytroyarmak** [comment]
Yes, I can do it. 
Actually, there is PR  #4 with this feature from @jshthornton, but due to conflicts, I've closed it. 
I'll recreate and merge it soon.

**Comment by dmytroyarmak** [comment]
@TrejGun I've just published v1.1.0 with this feature

**Comment by TrejGun** [comment]
thanks a lot
