### ISSUE TITLE
Help: Is there a simple way to disable all buttons?

### ISSUE THREAD

**Issue by FilipChalupa** [ultimate-pagination/react-ultimate-pagination#15]
Can you please help me figure this out? I have the `ultimate-pagination` hooked up to ajax requests. Each button (page number, first, last, next, prev) triggers one. Since my backend can be rather slow I have easily many concurrent requests resulting in flashing ui. Canceling `fetch()` in javascript is complicated right now so I came up with an idea to disable the pagination while a request is pending. The only solution I can think of is creating another Pagination component with `createUltimatePagination` and `itemTypeToComponent` set all to disabled buttons, but I don't believe it is a good approach.

**Comment by dmytroyarmak** [comment]
@Onset It's interesting use-case. I haven't thought about disabling pagination before.
Unfortunately, there is no nice way to do it right now, but I'm going to implement this feature.

**Comment by dmytroyarmak** [comment]
@Onset it should be available in v1.2.0

**Comment by FilipChalupa** [comment]
@dmytroyarmak Awesome. Thank you. It works great. I appreciate your quick action.

**Comment by B-R-Bender** [comment]
Does react-ultimate-pagination-bootstrap-3 component respect disabled property?
Try this https://codepen.io/anon/pen/ZVBaqW#anon-login

**Comment by dmytroyarmak** [comment]
@B-R-Bender Yes, it respects (but after 1.1.1 version) but visually components don't look disabled:
https://codepen.io/dmytroyarmak/pen/oJGdzv

I've created issue to fix it https://github.com/ultimate-pagination/react-ultimate-pagination-bootstrap-3/issues/4

**Comment by dmytroyarmak** [comment]
@B-R-Bender I've fixed it on v1.2.0 of react-ultimate-pagination-bootstrap-3
https://codepen.io/dmytroyarmak/pen/QzqrMQ

**Comment by B-R-Bender** [comment]
@dmytroyarmak tnx a lot :)
