### ISSUE TITLE
Hide previous or next buttons when on first or last page respectively.

### ISSUE THREAD

**Issue by sumeetkate** [ultimate-pagination/react-ultimate-pagination#17]
Is there a way we can hide previous button when on first page. 
Similarly hide next button when on last page.

**Comment by sumeetkate** [comment]
function NextPageLink(props) {
 if (props.isActive === false )
  // show button
 else 
 // do no show button
}

Shouldn't isActive return false when end of the list ?

**Comment by dmytroyarmak** [comment]
@sumeetkate yes, you should be able to use `isActive` property. On the first page, it should be "true" for the previous button and on the last page - for next button.

**Comment by sumeetkate** [comment]
@dmytroyarmak : Thanks closing the issue.
