### ISSUE TITLE
Ability to change how many page links are displayed

### ISSUE THREAD

**Issue by Inumedia** [ultimate-pagination/react-ultimate-pagination#2]
Currently it seems like there's no way to change the amount of pages that are displayed, it's always:

First page, Previous Page, Page 1, ... , Page 5, Page 6 (Current), Page 7, ..., Page 12345, Next Page, Last Page

This could just be a lack of documentation, but this is a feature I would like to have. 👍

**Comment by dmytroyarmak** [comment]
Yeah, currently there is no way to configure it. 
I was also thinking about this feature, so, I think, I can do it in the next release.

**Comment by nippur72** [comment]
In case, will this land in `ultimate-pagination` ? (I mean the generic component, not just `react`).

**Comment by dmytroyarmak** [comment]
@nippur72 Yeah, it should be added to`ultimate-pagination` library and then to `react-ultimate-pagination`. I hope, today I'll have a time for it.

**Comment by dmytroyarmak** [comment]
@Inumedia I've finally implemented it :)
it's available from version 1.0.0
http://ultimate-pagination.github.io/react-ultimate-pagination-examples/
