### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by FareedGuru** [ultimate-pagination/react-ultimate-pagination#28]
Module not found: Error: Can't resolve 'react-ultimate-pagination'

**Comment by maxbronnikov10** [comment]
plus for this issue. pls fix this - https://github.com/ultimate-pagination/react-ultimate-pagination/blob/master/package-lock.json#L7.
@dmytroyarmak

**Comment by maxbronnikov10** [comment]
guys, i can try my fork. https://www.npmjs.com/package/@maxbronnikov/react-ultimate-pagination. but maybe main collaborator fix this in new version, idk

**Comment by dmytroyarmak** [comment]
> plus for this issue. pls fix this - https://github.com/ultimate-pagination/react-ultimate-pagination/blob/master/package-lock.json#L7. @dmytroyarmak

It's a valid format for `lockfileVersion: 2` that is used by npm v7:
https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

**Comment by dmytroyarmak** [comment]
I've just tested the latest version with `node 10 + npm v6` and `node 16 + npm v9` and I have no problems 🤷‍♂️ 

@FareedGuru Could you please specify which version of node and npm you used? 
And also at what moment did you get the error?

You could also try to temporary use `v1.3.0` if you don't need react 18 support

**Comment by ajaimaxwel-pmd** [comment]
I'm also facing the same import issue, with node 12,  after the last release, let me see if I could provide more details...

**Comment by dmytroyarmak** [comment]
Sorry, my bad. The problem was caused by missed `lib` and `dist` folders in the build package.
I've just published `v1.3.2`. Could you please verify that it's fine now?

**Comment by gjvoosten** [comment]
For me, `v1.3.2` corrects the problems introduced by `v1.3.1`, thanks @dmytroyarmak !

**Comment by ajaimaxwel-pmd** [comment]
@dmytroyarmak thanks for fixing it 🙏
