### ISSUE TITLE
Error after upgrading to React 15.4.1

### ISSUE THREAD

**Issue by vivekmarakana** [ultimate-pagination/react-ultimate-pagination#3]
```
Warning: React.createElement: type should not be null, undefined, boolean, or number. 
It should be a string (for DOM elements) or a ReactClass (for composite components).
Check the render method of `UltimatePaginationComponent`.
```

**Comment by dmytroyarmak** [comment]
Hi @vivekmarakana 
I think it's not related to updating of React. It looks like one of the components hasn't been passed to `ReactUltimatePagination.createUltimatePagination`.
Most probably it's related to recent fix of a typo in name of "previous page link".
Before `react-ultimate-pagination` of `0.9.0` it was `PREVIOS_PAGE_LINK` and now in `0.9.0` it's fixed to `PREVIOUS_PAGE_LINK` (letter `U` was missed).
Please check your code and comment if it helps.

**Comment by vivekmarakana** [comment]
Thanks. That resolved the issue.

**Comment by dmytroyarmak** [comment]
You are welcome.
Anyway, I think it will be great to improve error handling in the library for this case.
